module.exports = {
  name: process.env.TYPEORM_SCHEMA,
  type: process.env.TYPEORM_CONNECTION,
  host: process.env.TYPEORM_HOST,
  port: process.env.TYPEORM_PORT,
  username: process.env.TYPEORM_USERNAME,
  password: process.env.TYPEORM_PASSWORD,
  database: process.env.TYPEORM_DATABASE,
  charset: process.env.TYPEORM_CHARSET,
  timezone: "+1:00",
  synchronize: process.env.TYPEORM_SYNCHRONIZE,
  dropSchema: process.env.TYPEORM_DROP_SCHEMA,
  entities: process.env.TYPEORM_ENTITIES,
  migrations: process.env.TYPEORM_MIGRATIONS,
  subscribers: process.env.TYPEORM_SUBSCRIBERS,
};
